version: '2'
services:
  influxdb:
    image: influxdb/influxdb
    ports:
     - "3000:3000"
    hostname: localhost

  grafana:
    image: grafana/grafana
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
    hostname: localhost
